// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHnqtHCJr1XGhhS6mnKJlZK2VCtlO-vlM',
    appId: '1:713405357856:web:ba079f549e5fd98d0fc145',
    messagingSenderId: '713405357856',
    projectId: 'devilmath1-f007e',
    authDomain: 'devilmath1-f007e.firebaseapp.com',
    storageBucket: 'devilmath1-f007e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGFc4W-X8PXmC-u4XCk6h6urE7dAWPLqU',
    appId: '1:713405357856:android:ce07bb14c3aa82080fc145',
    messagingSenderId: '713405357856',
    projectId: 'devilmath1-f007e',
    storageBucket: 'devilmath1-f007e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhfNndk047gjqwtGA7zQJ0MNttvFsIY5w',
    appId: '1:713405357856:ios:983874dcc7fe27190fc145',
    messagingSenderId: '713405357856',
    projectId: 'devilmath1-f007e',
    storageBucket: 'devilmath1-f007e.appspot.com',
    iosBundleId: 'com.example.devilmath1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhfNndk047gjqwtGA7zQJ0MNttvFsIY5w',
    appId: '1:713405357856:ios:7fb0a2cb0b0fe21f0fc145',
    messagingSenderId: '713405357856',
    projectId: 'devilmath1-f007e',
    storageBucket: 'devilmath1-f007e.appspot.com',
    iosBundleId: 'com.example.devilmath1.RunnerTests',
  );
}
